version: '3'

services:
  mysql.docker:
    image: mysql:8
    ports:
      - "3360:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command: ["--default-authentication-plugin=mysql_native_password"]